name: Build, Push Docker Image and Update Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t wijdanali/pixellence:latest .
        docker push wijdanali/pixellence:latest

    - name: Setup Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

    - name: Update Kubernetes deployment image
      run: |
        kubectl set image deployment/pixellence-deployment pixellence=wijdanali/pixellence:latest
